# Generated by Django 4.2.5 on 2023-10-14 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=50)),
                ('company_address', models.TextField()),
                ('company_website', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=50)),
                ('year', models.PositiveIntegerField()),
                ('Mode', models.CharField(max_length=50)),
                ('Description', models.TextField()),
                ('Stripend', models.IntegerField()),
                ('Duration', models.IntegerField()),
                ('PPO', models.CharField(max_length=50)),
                ('certificate', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Internal_Mentor', models.CharField(max_length=50)),
                ('External_Mentor', models.CharField(max_length=50)),
                ('Mobile', models.IntegerField()),
                ('Email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('Roll_No', models.IntegerField(primary_key=True, serialize=False)),
                ('Academic_Year', models.CharField(max_length=50)),
                ('Name', models.CharField(max_length=50)),
                ('Divison', models.CharField(max_length=50)),
                ('Department', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('Mobile', models.IntegerField()),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.company')),
                ('internship_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.internship')),
                ('mentor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.mentor')),
            ],
        ),
    ]
