# Generated by Django 4.2.5 on 2023-10-15 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='Divison',
            new_name='Division',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='company_id',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='internship_id',
            new_name='internship',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='mentor_id',
            new_name='mentor',
        ),
    ]
