# Generated by Django 4.2.5 on 2023-10-15 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_rename_divison_student_division_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='Mobile',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='Mobile',
            field=models.CharField(max_length=10),
        ),
    ]
